name: Java CI with Gradle

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest
    permissions:
      contents: read

    steps:
    - uses: actions/checkout@v4
    - name: Set up JDK 8
      uses: actions/setup-java@v4
      with:
        java-version: '8'
        distribution: 'temurin'

    - name: Setup Gradle
      uses: gradle/actions/setup-gradle@417ae3ccd767c252f5661f1ace9f835f9654f2b5 # v3.1.0

    - name: Fix Gradle No Permission
      run: chmod +x ./gradlew

    - name: Auto IQBooster
      run: cp -r ./iqboost/onGradleBuild_Could_not_resolve_forgeBin/.gradle ./gradle
      
    - name: Build DarkNya
      run: ./gradlew build

    - name: Upload Artifact
      uses: actions/upload-artifact@v2
      with:
        name: DarkNya
        path: build/libs/*.jar